basic_settings:
  site_title: Kostya.
  favicon_image: /images/puzzle.png

header_settings:
  logo_image: #/images/logo.png
  logo_width: 120

hero_settings:
  background_image: /images/7.svg

menu_settings:
  menu_items:
    - title: 'Blog'
      url: '/blog/'


footer_settings:
  site_title: Kostya Farber
  tagline: For the love of Lovelace, embrace poetical science.

post_settings:
  grid_spacing: 10

contact_settings:
  email_address: 'kostya.farber@gmail.com'
  form_action: 'https://formspree.io/f/xnqowyyy'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Get in Touch'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: 'https://kostya-farber.medium.com/'
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/kostyafarber'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/kostyafarber/'

color_settings:
  background_color: '#000000'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#ffffff'
  text_medium_color: '#6C7A89'
  text_light_color: '#AEB3BB'
  accent_color: '#4C60E6'
  border_color: '#ECEDEF'
  error_color: '#D64541'

font_settings:
  title_font: 'Founders Grotesk bold'
  body_font: 'Founders Grotesk light'
  regular_weight: 400
  bold_weight: 700
  site_title:
    small_size: 2 
    medium_size: 2
    large_size: 2
    weight: 700
    letter_spacing: -0.08
  menu:
    small_size: 0.75
    medium_size: 0.75
    large_size: 0.75
    weight: 600
    letter_spacing: -0.08
  h1:
    size: 7.986
    size_small: 4.13
    weight: 700
    letter_spacing: -0.04
    letter_spacing_small: -0.04
    line_height: 0.85
    line_height_small: 0.85
  h2:
    size: 4.5
    size_small: 2.035
    weight: 700
    letter_spacing: -0.04
    letter_spacing_small: -0.04
    line_height: 0.65
    line_height_small: 0.75 
  h3:
    size: 3.16
    size_small: 2.5
    weight: 700
    letter_spacing: -0.04
    letter_spacing_small: -0.04
    line_height: 0.65 
    line_height_small: 1
  h4:
    size: 2.117
    size_small: 1
    weight: 700
    letter_spacing: -0.04
    letter_spacing_small: -0.04
    line_height: 0.8
  h5:
    small_size: 1.8
    medium_size: 1.5
    large_size: 1
    weight: 700
    letter_spacing: -0.04
    line_height: 0.8
  h6:
    small_size: 1.5
    medium_size: 1.5
    large_size: 
    weight: 700
    letter_spacing: -0.04
    line_height: 0.8
  subtitle:
    size: 2
    size_small: 1
    weight_regular: 400
    weight_heavy: 500
    letter_spacing: -0.06
    letter_spacing_small: -0.06
    line_height: 1
    line_height_small: 1.5
  p:
    size: 1.25
    size_small: 1
    weight: 300
    letter_spacing: 0.02
    letter_spacing_small: 0
    line_height: 1.5
  p_small:
    size: 1
    size_small: 1 
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  label:
    size: 2
    small_size: 1
    weight: 500
    letter_spacing: -0.04
    small_letter_spacing: -0.04
    line_height: 1
  footnote:
    size: 1.15
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  blockquote:
    small_size: 1.75
    medium_size: 2
    large_size: 1.75
    weight: 500
    letter_spacing: -0.02
    line_height: 1.5
  buttons:
    weight: 500
    letter_spacing: -0.03

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""