source 'https://rubygems.org'

gem 'jekyll'
gem "kramdown-parser-gfm"
gem 'webrick'
gem 'github-pages'
gem "jekyll-jupyter-notebook"
gem 'jekyll-gist'

group :jekyll_plugins do
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
end